### ISSUE TITLE
PERFIL USUARIO

### ISSUE THREAD

**Issue by GilbertoMV** [JPchipres/appmaquitia#16]
Descripción:
Se deberá mejorar la vista de perfil de usuario de la siguiente manera:
    1. Agregar un ImageView que se rellene de manera aleatoria con 3 "avatares" diferentes establecidos mediante codigo.
        1.1 las imagenes de los avatares deberan seguir un diseño (el que sea), se almacenan localmente en la app, no en firestore.
    3. Agregar un boton de cerrar sesión.
    4. Agregar un boton de cambiar contraseña.
        3.1 El boton directamente enviará el correo al email del usuario y mostrará una alerta dependiendo si se envio correctamente o no
    5. Agregar un textview que muestre el correo registrado.
    6. Agregar un boton que muestre el historial de donaciones del usuario.
        5.1 El historial se mostrara en forma de popup no en un activity
       
   (en whatsapp se adjunta una imagen de ejemplo de diseño)

**Comment by JPchipres** [comment]
#RESUELTO-PENDIENTE TRANSACCIONES
