### ISSUE TITLE
Resolver Roles

### ISSUE THREAD

**Issue by GilbertoMV** [JPchipres/appmaquitia#21]
Descripción:
se agregará la logica necesaria para resolver los siguientes problemas:
1. Login usuario y organización funcionan para ambos (el login de ong lo puede usar un usuario y al reves)
2. el usuario logueado ve la vista de organización logueada
3. el visitante tiene acceso a ventanas exclusivas de usuarios u ongs

**Comment by JPchipres** [comment]
Resuelto
